### ISSUE TITLE
 Is this project in need to assistance? It also seems abandoned

### ISSUE THREAD

**Issue by atcol** [snuna/rusticnotion#9]
I am willing to help out with maintenance. There are two simple PRs that could be merged and released if someone is able to review?

**Comment by b3ngg** [comment]
Hey there,

I am so sorry. Somehow I didn't have notifications turned on, and I didn't expect people to actually contribute. I just stumbled upon this repo again by chance and was shocked to see PRs.

I know it doesn't look good for a "maintained" fork…

Notifications should work again now, and I am planning to put some work into this repo again.

If you're still interested, I would be happy to have you on board. Especially since I don't really have experience in open source, any help is welcome.

**Comment by atcol** [comment]
No need to apologise! It happens plus we're all busy.

Thanks for merging my other MR. 

Do you have a roadmap or any other such list of plans?

**Comment by b3ngg** [comment]
Not really yet. The goal, of course, is to be fully compatible with the Notion API as it changes. But I don't have an overview right now of what needs to be fixed in particular. That would probably be a good first step.  
I think a lot of work could also be done to improve the developer experience when updating or inserting in Notion.  

Right now, I am making a PR to add page icons (with the newly added custom emojis), followed by one for the unique ID property.  

I am actively using this crate in a project where all kinds of problems come up. So the plan was to fix them here instead of just for this project.  
Right now, I am picking up this project after a long pause, so that's why I visited this repo again…

**Comment by b3ngg** [comment]
Just invited you as a maintainer; feel free to help out where you can.

**Comment by atcol** [comment]
Sounds sensible. I am also using it on a side project so that will suggest some new integrations/fixes that might be required. Will MR as appropriate. Thanks
